Repository Gary-Community-Ventures/benefits-calculator, pull requests merged in 2023-12, with the labels that each got.

#767 Update Citizen Filter With Other Categories
  src/Assets/citizenshipFilterFormControlLabels.tsx
  src/Components/FilterSection/CitizenshipPopover.css
  src/Components/FilterSection/CitizenshipPopover.tsx
  src/Components/Results/Results.tsx
Labels: impact-medium

#768 Fix 211 Header Language Select
  src/Components/TwoOneOneComponents/TwoOneOneHeader/TwoOneOneHeader.js
Labels: impact-low

#773 Blank Assets
  src/Assets/updateScreen.ts
Labels: impact-low

#794 Add Individual Headers for All Questions
  src/Assets/questions.tsx
  src/Components/QuestionComponentContainer/QuestionComponentContainer.js
  src/Types/Questions.ts
Labels: impact-medium

#771 Add MFB Loading GIF
  src/Assets/loading/loading-icon.png
  src/Assets/loading/logoLoading.gif
  src/Components/Loading/Loading.tsx
  src/Components/LoadingPage/LoadingPage.css
  src/Components/LoadingPage/LoadingPage.tsx
Labels: impact-low

#815 Refactor/header
  src/Components/Header/Header.css
  src/Components/Header/Header.js
  src/Components/Referrer/referrerHook.ts
Labels: impact-low

#814 211 Branding Updates
  src/App.css
  src/Assets/styleController.ts
  src/Components/CheckboxGroup/BasicCheckboxGroup.js
  src/Components/Confirmation/Confirmation.css
  src/Components/ErrorMessage/ErrorMessageWrapper.css
  src/Components/IncomeBlock/PersonIncomeBlock.js
  src/Components/LandingPage/LandingPage.css
  src/Components/LandingPage/LandingPage.tsx
  src/Components/OptionCardGroup/OptionCardGroup.css
  src/Components/ProgressBar/ProgressBar.tsx
  src/Components/Results/Results.css
  src/Components/ResultsError/ResultsError.css
  src/Components/Textfield/Textfield.js
  src/Components/TwoOneOneComponents/TwoOneOneHeader/TwoOneOneHeader.css
  src/Components/TwoOneOneComponents/TwoOneOneHeader/TwoOneOneHeader.js
Labels: impact-high

#811 Add New Languages
  src/Assets/languageOptions.tsx
Labels: impact-medium

#809 Lets Get Set Logo
  src/Assets/LetsGetSet/lgsLogo.png
  src/Assets/referralOptions.tsx
  src/Components/Referrer/referrerHook.ts
Labels: impact-low

#808 Email Error
  src/App.tsx
  src/Assets/pageTitleTags.ts
  src/Assets/updateScreen.ts
  src/Assets/validationFunctions.tsx
  src/Components/ErrorMessage/ErrorMessageWrapper.css
  src/Components/ErrorMessage/ErrorMessageWrapper.tsx
  src/Components/SignUp/SignUp.js
  src/Types/ErrorController.ts
  src/Types/FormData.ts
Labels: impact-medium

#788 Add Branded Results Header
  src/Components/Referrer/Referrer.tsx
  src/Components/Results/Results.tsx
Labels: impact-low

#818 Branding Fixes
  src/App.css
  src/Assets/questions.tsx
  src/Assets/styleController.ts
  src/Components/IncomeBlock/PersonIncomeBlock.js
  src/Components/ProgressBar/ProgressBar.tsx
  src/Components/Results/Results.css
Labels: bug
