Repository Gary-Community-Ventures/benefits-calculator, pull requests merged in 2023-09, with the labels that each got.

#622 Remove/unemployed and vet status
  src/Assets/Languages/English.json
  src/Assets/Languages/Spanish.json
  src/Assets/Languages/Vietnamese.json
  src/Assets/conditionOptions.js
  src/Assets/devFormData.js
  src/Assets/updateScreen.js
  src/Components/Confirmation/Confirmation.js
  src/Components/FetchScreen/FetchScreen.js
  src/Components/HouseholdDataBlock/HouseholdDataBlock.js
  src/Components/SubmitScreen/SubmitScreen.js
  src/Types/FormData.ts
  src/Types/Language.ts
Labels: impact-medium

#624 Add jeffcohscm Route
  src/App.tsx
  src/Components/Header/Header.js
  src/Components/JeffcoComponents/JeffcoLandingPage/JeffcoLandingPage.tsx
Labels: impact-medium

#625 Feat/age checkbox
  src/Assets/Languages/English.json
  src/Assets/Languages/Spanish.json
  src/Assets/Languages/Vietnamese.json
  src/Assets/updateScreen.js
  src/Components/FetchScreen/FetchScreen.js
  src/Components/Header/Header.css
  src/Components/LandingPage/LandingPage.tsx
  src/Components/Wrapper/Wrapper.tsx
  src/Types/FormData.ts
  src/Types/Language.ts
Labels: impact-medium

#627 Change Header Words
  src/Assets/Languages/English.json
  src/Assets/Languages/Spanish.json
  src/Assets/Languages/Vietnamese.json
  src/Components/Results/Results.js
Labels: impact-low

#630 Replace favicon icon
  public/favicon.ico
Labels: impact-low

#633 Add Village Exchange Header
  src/Assets/VillageExchange/villageExchangeLogo.png
  src/Assets/referralOptions.tsx
  src/Components/Header/Header.css
  src/Components/Header/Header.js
Labels: impact-low

#632 Translations
  src/App.tsx
  src/Assets/Languages/English.json
  src/Assets/Languages/Spanish.json
  src/Assets/Languages/Vietnamese.json
  src/Components/Confirmation/Confirmation.js
  src/Components/FetchScreen/FetchScreen.css
  src/Components/FetchScreen/FetchScreen.js
  src/Components/FilterSection/FilterSection.tsx
  src/Components/FilterSection/OtherPopover.tsx
  src/Components/LandingPage/LandingPage.tsx
  src/Components/LoadingPage/LoadingPage.css
  src/Components/LoadingPage/LoadingPage.tsx
  src/Components/OptionCardGroup/OptionCardGroup.js
  src/Components/Radiofield/HHDataRadiofield.js
  src/Components/Radiofield/Radiofield.js
  src/Components/Results/Results.tsx
  src/Components/TwoOneOneComponents/TwoOneOneHeader/TwoOneOneHeader.js
  src/Components/UrgentNeedsTable/UrgentNeedsRow.tsx
  src/Components/UrgentNeedsTable/UrgentNeedsTable.tsx
  src/Components/Wrapper/Wrapper.tsx
  src/Types/Results.ts
  src/Types/WrapperContext.ts
  src/apiCalls.js
Labels: impact-high

#628 Feat/table row dd icon
  src/Components/Results/Results.tsx
Labels: impact-medium

#629 Feat/211 footer a11y
  src/Components/TwoOneOneComponents/TwoOneOneFooter/TwoOneOneFooter.tsx
Labels: impact-low

#634 Refactor the defaultMessage for housing
  src/Assets/acuteConditionOptions.tsx
Labels: impact-low

#635 Refactor Referrer Code Logic
  src/App.tsx
  src/Assets/questions.tsx
  src/Assets/stepDirectory.js
  src/Assets/stepDirectory.ts
  src/Components/Confirmation/Confirmation.js
  src/Components/FollowUpQuestions/FollowUpQuestions.js
  src/Components/Header/Header.js
  src/Components/HouseholdDataBlock/HouseholdDataBlock.js
  src/Components/NoResultsTable/NoResultsTable.tsx
  src/Components/PreviousButton/PreviousButton.js
  src/Components/ProgressBar/ProgressBar.tsx
  src/Components/QuestionComponentContainer/QuestionComponentContainer.js
  src/Components/Referrer/Referrer.tsx
  src/Components/Referrer/referrerHook.ts
  src/Components/Share/Share.js
  src/Components/UrgentNeedsTable/UrgentNeedsTable.tsx
  src/Components/Wrapper/Wrapper.tsx
  src/Types/WrapperContext.ts
Labels: impact-medium

#636 Fix Import
  src/Assets/questions.tsx
Labels: impact-low

#637 Fix 211 Theme
  src/App.tsx
  src/Components/Referrer/referrerHook.ts
Labels: impact-low

#638 Add Referrer Source Question Back
  src/Assets/stepDirectory.ts
Labels: impact-low
