Repository Gary-Community-Ventures/benefits-calculator, pull requests merged in 2023-10, with the labels that each got.

#643 Rename Child Care Youth and Education Category
  src/Components/Results/Results.tsx
Labels: impact-low

#644 Feat/update citizen filters
  src/Assets/citizenshipFilterFormControlLabels.tsx
  src/Components/FilterSection/CitizenshipPopover.js
  src/Components/FilterSection/CitizenshipPopover.tsx
  src/Components/FilterSection/FilterSection.tsx
  src/Components/NoResultsTable/NoResultsTable.css
  src/Components/NoResultsTable/NoResultsTable.tsx
  src/Components/Results/Results.tsx
Labels: impact-high

#645 Use Different Chat Link for 211
  src/Components/TwoOneOneComponents/TwoOneOneFooter/TwoOneOneFooter.tsx
Labels: impact-low

#646 Updated biamfbcombinedlogo
  src/Assets/biamfbcombinedlogo.png
Labels: impact-low

#647 Remove Unused Referral Sources
  src/Assets/referralOptions.tsx
Labels: impact-low

#648 Move PTC to Housing and Utilities Category
  src/Assets/BenefitCategoryLists/cashAssistanceBenefits.tsx
  src/Assets/BenefitCategoryLists/childCareBenefits.tsx
  src/Assets/BenefitCategoryLists/foodAndNutritionBenefits.tsx
  src/Assets/BenefitCategoryLists/healthCareBenefits.tsx
  src/Assets/BenefitCategoryLists/housingAndUtilities.tsx
  src/Assets/BenefitCategoryLists/taxCreditBenefits.tsx
  src/Assets/BenefitCategoryLists/transportationBenefits.tsx
  src/Assets/benefitCategories.tsx
  src/Assets/benefitOptions.js
  src/Components/AccordionsContainer/AccordionsContainer.js
Labels: impact-low

#649 Add Edit Icon to Household Members
  src/Components/HouseholdDataBlock/HouseholdDataBlock.css
  src/Components/HouseholdDataBlock/HouseholdDataBlock.js
Labels: impact-low

#650 Feat/updated citizen filters
  src/Assets/citizenshipFilterFormControlLabels.tsx
  src/Components/FilterSection/CitizenshipPopover.css
  src/Components/FilterSection/CitizenshipPopover.tsx
  src/Components/FilterSection/FilterSection.tsx
  src/Components/Results/Results.tsx
  src/Types/Results.ts
Labels: impact-medium

#651 Change Accordion Header
  src/Assets/benefitCategories.tsx
Labels: impact-low

#655 Use Smaller BIA Logo
  src/Assets/biamfbcombinedlogo.png
Labels: impact-low

#656 Refactor/results header
  src/Components/Results/Results.tsx
Labels: impact-low

#670 Results Sub Header
  src/App.tsx
  src/Components/EmailResults/EmailResults.css
  src/Components/EmailResults/EmailResults.tsx
  src/Components/Results/Results.css
  src/Components/Results/Results.tsx
Labels: impact-low

#671 Use utm_source as a Backup to referrer
  src/App.tsx
Labels: impact-medium

#679 Add French and Amharic
  src/Assets/languageOptions.tsx
  src/Components/Header/Header.js
  src/Components/Results/Results.tsx
Labels: impact-medium
