Repository Gary-Community-Ventures/benefits-calculator, pull requests merged in 2023-07, with the labels that each got.

#588 Add 211co to referralOptions
  src/Assets/referralOptions.js
Labels: impact-low

#589 Shrink Logo On Smaller Screen Sizes
  src/Components/Header/Header.css
  src/Components/Header/Header.js
Labels: impact-medium

#590 Refactor/hhdb member cards
  src/Components/Disclaimer/Disclaimer.css
  src/Components/Disclaimer/Disclaimer.js
  src/Components/HouseholdDataBlock/HouseholdDataBlock.js
Labels: impact-high

#591 Switch Theme
  src/App.css
  src/App.tsx
  src/Assets/acuteConditionOptions.js
  src/Assets/styleController.ts
  src/Assets/styleOverrides.js
  src/Assets/validationFunctions.js
  src/Components/CategoryAccordion/CategoryAccordion.js
  src/Components/CustomSwitch/CustomSwitch.js
  src/Components/EmailResults/EmailResults.css
  src/Components/ExpenseBlock/ExpenseQuestion.js
  src/Components/FilterSection/CitizenshipPopover.js
  src/Components/FilterSection/FilterSection.css
  src/Components/FilterSection/FilterSection.js
  src/Components/FilterSection/OtherPopover.css
  src/Components/HouseholdDataBlock/HouseholdDataBlock.css
  src/Components/HouseholdDataBlock/HouseholdDataBlock.js
  src/Components/IncomeBlock/IncomeBlock.css
  src/Components/IncomeBlock/IncomeQuestion.js
  src/Components/LandingPage/LandingPage.css
  src/Components/Loading/Loading.css
  src/Components/OptionCardGroup/OptionCardGroup.js
  src/Components/ProgressBar/ProgressBar.css
  src/Components/ProgressBar/ProgressBar.tsx
  src/Components/QuestionComponentContainer/QuestionComponentContainer.css
  src/Components/Results/Results.css
  src/Components/Results/Results.js
  src/Components/ResultsError/ResultsError.css
  src/Components/Share/Share.css
  src/Components/Table/Table.js
  src/Components/Wrapper/Wrapper.tsx
  src/Types/FormData.ts
  src/Types/WrapperContext.ts
  src/index.css
  src/index.tsx
Labels: impact-high

#592 Wrap the edit icons with a button
  src/Components/Confirmation/Confirmation.js
Labels: impact-low

#597 Feat/hamburger menu
  src/App.css
  src/App.tsx
  src/Assets/Languages/English.json
  src/Assets/Languages/Spanish.json
  src/Assets/Languages/Vietnamese.json
  src/Assets/styleController.ts
  src/Assets/twoOneOneLinks.js
  src/Assets/twoOneOneMFBLogo.png
  src/Components/Header/Header.css
  src/Components/Header/Header.js
  src/Components/TwoOneOneComponents/TwoOneOneHeader/TwoOneOneHeader.css
  src/Components/TwoOneOneComponents/TwoOneOneHeader/TwoOneOneHeader.js
  src/Types/Language.ts
Labels: impact-high
