Repository Gary-Community-Ventures/benefits-calculator, pull requests merged in 2023-08, with the labels that each got.

#600 Add/immediate needs categories
  src/Assets/Languages/English.json
  src/Assets/Languages/Spanish.json
  src/Assets/Languages/Vietnamese.json
  src/Assets/OptionCardIcons/briefcase.png
  src/Assets/OptionCardIcons/dentistry.png
  src/Assets/OptionCardIcons/gavel.png
  src/Assets/acuteConditionOptions.js
  src/Assets/devFormData.js
  src/Assets/updateScreen.js
  src/Components/FetchScreen/FetchScreen.js
  src/Components/SubmitScreen/SubmitScreen.js
  src/Components/Wrapper/Wrapper.tsx
  src/Types/FormData.ts
  src/Types/Language.ts
Labels: impact-medium

#598 Refactored Error Messages
  package-lock.json
  src/Assets/Languages/English.json
  src/Assets/Languages/Spanish.json
  src/Assets/Languages/Vietnamese.json
  src/Assets/questions.js
  src/Assets/validationFunctions.js
  src/Assets/validationFunctions.tsx
  src/Components/AccordionsContainer/AccordionsContainer.js
  src/Components/Disclaimer/Disclaimer.js
  src/Components/DropdownMenu/BasicSelect.js
  src/Components/DropdownMenu/BasicSelect.tsx
  src/Components/DropdownMenu/DropdownMenu.js
  src/Components/DropdownMenu/DropdownMenu.tsx
  src/Components/EmailResults/EmailResults.js
  src/Components/ErrorMessage/ErrorMessageWrapper.css
  src/Components/ErrorMessage/ErrorMessageWrapper.tsx
  src/Components/ExpenseBlock/ExpenseBlock.js
  src/Components/ExpenseBlock/ExpenseQuestion.js
  src/Components/FollowUpQuestions/FollowUpQuestions.js
  src/Components/HouseholdDataBlock/HouseholdDataBlock.js
  src/Components/IncomeBlock/IncomeBlock.js
  src/Components/IncomeBlock/IncomeQuestion.js
  src/Components/QuestionComponentContainer/QuestionComponentContainer.js
  src/Components/SignUp/SignUp.js
  src/Components/Textfield/Textfield.js
  src/Types/ErrorController.ts
Labels: impact-medium

#601 merge
  src/App.tsx
  src/Assets/questions.js
  src/Components/AccordionsContainer/AccordionsContainer.js
  src/Components/DropdownMenu/DropdownMenu.tsx
  src/Components/EmailResults/EmailResults.js
  src/Components/ExpenseBlock/ExpenseBlock.js
  src/Components/ExpenseBlock/ExpenseQuestion.js
  src/Components/HouseholdDataBlock/HouseholdDataBlock.js
  src/Components/IncomeBlock/IncomeBlock.js
  src/Components/IncomeBlock/IncomeQuestion.js
  src/Components/QuestionComponentContainer/QuestionComponentContainer.js
  src/Components/SignUp/SignUp.js
  src/Components/Textfield/Textfield.js
Labels: impact-low

#610 Make Referrer Source from URL Show Up in Other
  src/App.tsx
Labels: impact-low

#608 Scroll to the Tof the Page On Error and On Continue
  src/Components/HouseholdDataBlock/HouseholdDataBlock.js
Labels: impact-low

#606 Refactor/referral spouse lang
  src/Assets/Languages/Spanish.json
  src/Assets/referralOptions.tsx
Labels: impact-low

#607 Don't Show Errors When Follow Up Questions Are Shown
  src/Components/Share/Share.js
Labels: impact-medium

#613 Feat/share referrer code
  src/Components/Share/Share.js
Labels: impact-low

#614 Added Google Analytics Script
  public/index.html
Labels: impact-low

#615 Remove Whitespace Characters
  public/index.html
Labels: impact-low

#616 Add UTM Trackers for Google Analytics
  src/Components/NoResultsTable/NoResultsTable.tsx
  src/Components/UrgentNeedsTable/UrgentNeedsTable.js
Labels: impact-low

#611 Refactor/steps zero one
  src/App.tsx
  src/Assets/JeffcoAssets/jeffcobrand.png
  src/Assets/JeffcoAssets/jeffcolandingpage.png
  src/Assets/Languages/English.json
  src/Assets/Languages/Spanish.json
  src/Assets/Languages/Vietnamese.json
  src/Assets/TwoOneOneAssets/twoOneOneMFBLogo.png
  src/Assets/devFormData.js
  src/Assets/referralOptions.tsx
  src/Assets/updateScreen.js
  src/Assets/validationFunctions.tsx
  src/Components/DropdownMenu/BasicSelect.tsx
  src/Components/DropdownMenu/DropdownMenu.tsx
  src/Components/FetchScreen/FetchScreen.js
  src/Components/Header/Header.js
  src/Components/JeffcoComponents/JeffcoLandingPage/JeffcoLandingPage.css
  src/Components/JeffcoComponents/JeffcoLandingPage/JeffcoLandingPage.tsx
  src/Components/LandingPage/LandingPage.js
  src/Components/LandingPage/LandingPage.tsx
  src/Components/Share/Share.js
  src/Components/SubmitScreen/SubmitScreen.js
  src/Components/TwoOneOneComponents/TwoOneOneHeader/TwoOneOneHeader.css
  src/Components/TwoOneOneComponents/TwoOneOneHeader/TwoOneOneHeader.js
  src/Components/Wrapper/Wrapper.tsx
  src/Types/ErrorController.ts
  src/Types/FormData.ts
  src/Types/Language.ts
  tsconfig.json
Labels: impact-high

#617 Redirect From step-0 to step-1
  src/App.tsx
Labels: impact-high

#618 Change Colorado 211 to 211 Colorado
  src/Components/NoResultsTable/NoResultsTable.tsx
Labels: impact-low

#621 Use Google Tag Manager
  package-lock.json
  package.json
  src/App.tsx
  src/Assets/analytics.ts
  src/Components/HouseholdDataBlock/HouseholdDataBlock.js
  src/Components/LandingPage/LandingPage.tsx
  src/Components/Results/Results.js
  src/Components/Share/Share.js
  src/Components/UrgentNeedsTable/UrgentNeedsRow.js
Labels: impact-high

#623 Add Event Names
  src/App.tsx
  src/Components/LandingPage/LandingPage.tsx
  src/Components/Results/Results.js
  src/Components/Share/Share.js
  src/Components/UrgentNeedsTable/UrgentNeedsRow.js
Labels: impact-medium
