Repository Gary-Community-Ventures/benefits-calculator, pull requests merged in 2024-11, with the labels that each got.

#1353 Truncate the household member list if the user chooses a smaller household member size
  src/Components/Steps/HouseholdSize.tsx
Labels: bug, impact-medium, system-wide

#1352 Document Links
  src/Components/Results/ProgramPage/ProgramPage.css
  src/Components/Results/ProgramPage/ProgramPage.tsx
  src/Types/Results.ts
Labels: system-wide

#1377 Only allow integers in the household size field
  src/Components/Steps/HouseholdSize.tsx
Labels: impact-low

#1380 Remove unused components
  src/Components/NoResultsTable/NoResultsTable.css
  src/Components/NoResultsTable/NoResultsTable.tsx
  src/Components/Referrer/referrerHook.tsx
Labels: impact-low
