Repository Gary-Community-Ventures/benefits-calculator, pull requests merged in 2024-04, with the labels that each got.

#999 971/help bubble text
  src/Assets/questions.tsx
  src/Components/HelpBubbleIcon/HelpButton.tsx
  src/Components/HouseholdDataBlock/HouseholdDataBlock.js
  src/Components/IncomeBlock/PersonIncomeBlock.css
  src/Components/IncomeBlock/PersonIncomeBlock.js
Labels: ctd-reviewing

#1010 Fix Dollar Sign
  src/Components/Textfield/Textfield.js
Labels: impact-low

#1020 Feat/dev branch workflow
  .github/workflows/enforcer.yaml
Labels: impact-low

#1014 Don't Show Benefits That the Household Already Has
  src/Components/Results/Results.tsx
Labels: impact-medium

#1019 Fix Contact Validation
  .eslintrc.json
  src/Assets/updateScreen.ts
  src/Assets/validationFunctions.tsx
  src/Components/SignUp/SignUp.js
Labels: impact-high

#991 Refactor frontend config to backend
  src/App.tsx
  src/Assets/BenefitCategoryLists/benefitAccordions.ts
  src/Assets/BenefitCategoryLists/benefitCategories.tsx
  src/Assets/BenefitCategoryLists/categories/cashAssistanceBenefits.tsx
  src/Assets/BenefitCategoryLists/categories/childCareBenefits.tsx
  src/Assets/BenefitCategoryLists/categories/foodAndNutritionBenefits.tsx
  src/Assets/BenefitCategoryLists/categories/healthCareBenefits.tsx
  src/Assets/BenefitCategoryLists/categories/housingAndUtilities.tsx
  src/Assets/BenefitCategoryLists/categories/taxCreditBenefits.tsx
  src/Assets/BenefitCategoryLists/categories/transportationBenefits.tsx
  src/Assets/acuteConditionOptions.tsx
  src/Assets/coZipcodes.ts
  src/Assets/conditionOptions.tsx
  src/Assets/countiesByZipcode.tsx
  src/Assets/expenseOptions.tsx
  src/Assets/frequencyOptions.tsx
  src/Assets/healthInsuranceOptions.tsx
  src/Assets/housingOptions.tsx
  src/Assets/incomeOptions.tsx
  src/Assets/languageOptions.tsx
  src/Assets/questions.tsx
  src/Assets/referralOptions.tsx
  src/Assets/relationshipOptions.tsx
  src/Assets/signUpOptions.tsx
  src/Assets/updateScreen.ts
  src/Assets/validationFunctions.tsx
  src/Components/AccordionsContainer/AccordionsContainer.tsx
  src/Components/Config/configHook.tsx
  src/Components/Config/configHooks.tsx
  src/Components/Confirmation/Confirmation.js
  src/Components/DropdownMenu/BasicSelect.tsx
  src/Components/DropdownMenu/DropdownMenu.tsx
  src/Components/ExpenseBlock/ExpenseQuestion.js
  src/Components/FetchScreen/FetchScreen.tsx
  src/Components/FollowUpQuestions/FollowUpQuestions.js
  src/Components/Header/Header.js
  src/Components/HouseholdDataBlock/HouseholdDataBlock.js
  src/Components/IncomeBlock/IncomeQuestion.js
  src/Components/JeffcoComponents/JeffcoLandingPage/JeffcoLandingPage.tsx
  src/Components/QuestionComponentContainer/QuestionComponentContainer.js
  src/Components/SelectLanguagePage/SelectLanguagePage.tsx
  src/Components/Textfield/Textfield.js
  src/Components/TwoOneOneComponents/TwoOneOneHeader/TwoOneOneHeader.js
  src/Components/Wrapper/Wrapper.tsx
  src/Types/ApiFormData.ts
  src/Types/ErrorController.ts
  src/Types/Language.ts
  src/Types/Questions.ts
  src/Types/WrapperContext.ts
Labels: impact-high

#1016 Refactor/program pg
  src/Components/Results/ProgramPage/ProgramPage.css
  src/Components/Results/ProgramPage/ProgramPage.tsx
Labels: impact-low

#1023 Refactor/211 styles
  src/Assets/OptionCardIcons/checkmark.svg
  src/Components/OptionCardGroup/OptionCardGroup.css
  src/Components/Results/BackAndSaveButtons/BackAndSaveButtons.css
  src/Components/Results/Results.css
  src/Components/Results/ResultsHeader/ResultsHeader.tsx
  src/Components/TwoOneOneComponents/TwoOneOneHeader/TwoOneOneHeader.css
Labels: impact-low
