Repository Gary-Community-Ventures/benefits-calculator, pull requests merged in 2024-02, with the labels that each got.

#903 Feat/get ahead co
  src/Assets/GetAheadColorado/gaclogo.png
  src/Assets/referralOptions.tsx
  src/Components/Referrer/referrerHook.ts
Labels: impact-low

#893 Low Confidence In Program Type
  src/Types/Results.ts
Labels: impact-low

#902 Warning Message Type
  src/Types/Results.ts
Labels: impact-low

#866 Rebrand/cit filters
  src/Assets/citizenshipFilterFormControlLabels.tsx
  src/Components/Confirmation/Confirmation.css
  src/Components/Confirmation/Confirmation.js
  src/Components/FilterSection/CitizenshipPopover.css
  src/Components/FilterSection/CitizenshipPopover.tsx
  src/Components/FilterSection/FilterSection.css
  src/Components/FilterSection/FilterSection.tsx
  src/Components/FilterSection/OtherPopover.css
  src/Components/FilterSection/OtherPopover.tsx
  src/Components/Results/Programs/Filter.css
  src/Components/Results/Programs/Filter.tsx
  src/Components/Results/Results.css
  src/Components/Results/Results.tsx
  src/Components/Share/Share.css
Labels: impact-medium

#881 Rebrand/top buttons
  src/App.tsx
  src/Assets/save.svg
  src/Components/EmailResults/EmailResults.css
  src/Components/EmailResults/EmailResults.tsx
  src/Components/Results/BackAndSaveButtons/BackAndSaveButtons.css
  src/Components/Results/BackAndSaveButtons/BackAndSaveButtons.tsx
  src/Components/Results/Results.tsx
  src/Components/Results/ResultsHeader/ResultsHeader.tsx
Labels: impact-medium

#914 Warning Icon
  src/Assets/icons/benefits.svg
  src/Assets/icons/edit.svg
  src/Assets/icons/error-icon.svg
  src/Assets/icons/expenses.svg
  src/Assets/icons/head.svg
  src/Assets/icons/helpBubble.svg
  src/Assets/icons/household.svg
  src/Assets/icons/immediate.svg
  src/Assets/icons/referral.svg
  src/Assets/icons/residence.svg
  src/Assets/icons/resources.svg
  src/Assets/icons/warning.svg
  src/Components/BackToScreen/BackToScreen.css
  src/Components/BackToScreen/BackToScreen.tsx
  src/Components/Confirmation/Confirmation.js
  src/Components/HelpBubbleIcon/HelpButton.tsx
  src/Components/ResultsError/ResultsError.tsx
Labels: impact-low

#928 Refactor/income expense dd menus
  src/Assets/expenseOptions.tsx
  src/Assets/incomeOptions.tsx
Labels: impact-low

#915 Remove Mail Option
  src/Assets/referralOptions.tsx
Labels: impact-low

#927 Feat/new benefit flag
  src/Components/Results/211Button/211Button.css
  src/Components/Results/211Button/211Button.tsx
  src/Components/Results/Programs/ProgramCard.css
  src/Components/Results/Programs/ProgramCard.tsx
  src/Components/Results/Results.css
Labels: impact-low

#835 [WIP] Results Redesign
  .eslintrc.json
  public/index.html
  src/App.tsx
  src/Assets/CategoryHeadingIcons/cashAssistant.svg
  src/Assets/CategoryHeadingIcons/childCareYouthEducation.svg
  src/Assets/CategoryHeadingIcons/food.svg
  src/Assets/CategoryHeadingIcons/healthcare.svg
  src/Assets/CategoryHeadingIcons/housing.svg
  src/Assets/CategoryHeadingIcons/taxCredits.svg
  src/Assets/CategoryHeadingIcons/transportation.svg
  src/Assets/acuteConditionOptions.tsx
  src/Assets/citizenshipFilterFormControlLabels.tsx
  src/Assets/save.svg
  src/Components/Confirmation/Confirmation.css
  src/Components/Confirmation/Confirmation.js
  src/Components/EmailResults/EmailResults.css
  src/Components/EmailResults/EmailResults.tsx
  src/Components/FilterSection/CitizenshipPopover.css
  src/Components/FilterSection/CitizenshipPopover.tsx
  src/Components/FilterSection/FilterSection.css
  src/Components/FilterSection/FilterSection.tsx
  src/Components/FilterSection/OtherPopover.css
  src/Components/FilterSection/OtherPopover.tsx
  src/Components/LandingPage/LandingPage.tsx
  src/Components/NoResultsTable/NoResultsTable.tsx
  src/Components/OptionCardGroup/OptionCardGroup.css
  src/Components/Results/211Button/211Button.css
  src/Components/Results/211Button/211Button.tsx
  src/Components/Results/BackAndSaveButtons/BackAndSaveButtons.css
  src/Components/Results/BackAndSaveButtons/BackAndSaveButtons.tsx
  src/Components/Results/CategoryHeading/CategoryHeading.tsx
  src/Components/Results/Loading/Loading.css
  src/Components/Results/Loading/Loading.tsx
  src/Components/Results/Navigators/NavigatorCard.tsx
  src/Components/Results/Needs/NeedCard.tsx
  src/Components/Results/Needs/Needs.tsx
  src/Components/Results/ProgramPage/ProgramPage.css
  src/Components/Results/ProgramPage/ProgramPage.tsx
  src/Components/Results/Programs/Filter.css
  src/Components/Results/Programs/Filter.tsx
  src/Components/Results/Programs/ProgramCard.css
  src/Components/Results/Programs/ProgramCard.tsx
  src/Components/Results/Programs/Programs.tsx
  src/Components/Results/Results.css
  src/Components/Results/Results.tsx
  src/Components/Results/ResultsError/ResultsError.css
  src/Components/Results/ResultsError/ResultsError.tsx
  src/Components/Results/ResultsHeader/ResultsHeader.tsx
  src/Components/Results/Tabs/Tabs.tsx
  src/Components/Results/Translate/Translate.tsx
  src/Components/Share/Share.css
  src/Components/SignUp/SignUp.js
  src/Components/TwoOneOneComponents/TwoOneOneFooter/TwoOneOneFooter.tsx
  src/Components/TwoOneOneComponents/TwoOneOneHeader/TwoOneOneHeader.js
  src/Components/UrgentNeedsTable/UrgentNeedsRow.css
  src/Components/UrgentNeedsTable/UrgentNeedsRow.tsx
  src/Components/UrgentNeedsTable/UrgentNeedsTable.css
  src/Components/UrgentNeedsTable/UrgentNeedsTable.tsx
  src/Components/Wrapper/Wrapper.tsx
  src/Types/Results.ts
Labels: impact-high

#956 Results Redesign Fixes
  src/App.tsx
  src/Components/Results/Programs/Programs.tsx
  src/Components/Results/Results.css
  src/Components/Results/Results.tsx
  src/Components/Results/ResultsHeader/ResultsHeader.tsx
Labels: impact-high

#962 More bug fixes
  src/Assets/resultsConstants.ts
  src/Components/Results/CategoryHeading/CategoryHeading.tsx
  src/Components/Results/Needs/NeedCard.css
  src/Components/Results/Results.css
  src/Components/Results/Results.tsx
  src/Components/Results/ResultsHeader/ResultsHeader.tsx
Labels: impact-medium
