Repository Gary-Community-Ventures/benefits-calculator, pull requests merged in 2024-12, with the labels that each got.

#1376 White label routing
  src/App.tsx
  src/Assets/languageOptions.tsx
  src/Assets/questions.tsx
  src/Assets/updateScreen.ts
  src/Components/CcigComponents/CcigLandingPage.tsx
  src/Components/Config/configHook.tsx
  src/Components/Confirmation/Confirmation.js
  src/Components/CurrentBenefits/CurrentBenefits.tsx
  src/Components/FetchScreen/FetchScreen.tsx
  src/Components/Footer/Footer.tsx
  src/Components/Header/Header.js
  src/Components/HouseholdDataBlock/HouseholdDataBlock.js
  src/Components/JeffcoComponents/JeffcoLandingPage/JeffcoLandingPage.tsx
  src/Components/LoadingPage/LoadingPage.tsx
  src/Components/PreviousButton/PreviousButton.tsx
  src/Components/QuestionComponentContainer/QuestionComponentContainer.js
  src/Components/QuestionComponents/questionHooks.ts
  src/Components/Referrer/referrerDataInfo.tsx
  src/Components/Referrer/referrerHook.tsx
  src/Components/Referrer/useLogo.tsx
  src/Components/Results/211Button/211Button.tsx
  src/Components/Results/BackAndSaveButtons/BackAndSaveButtons.tsx
  src/Components/Results/ProgramPage/ProgramPage.tsx
  src/Components/Results/Programs/ProgramCard.tsx
  src/Components/Results/Results.tsx
  src/Components/Results/ResultsHeader/ResultsHeader.tsx
  src/Components/Results/Tabs/Tabs.tsx
  src/Components/RouterUtil/LanguageRouter.tsx
  src/Components/RouterUtil/RedirectToWhiteLabel.tsx
  src/Components/Steps/Disclaimer/Disclaimer.tsx
  src/Components/Steps/Referrer.tsx
  src/Components/Steps/SelectLanguagePage.tsx
  src/Components/Steps/SelectStatePage.tsx
  src/Components/Wrapper/Wrapper.tsx
  src/Types/ApiFormData.ts
  src/Types/FormData.ts
  src/Types/WrapperContext.ts
  src/apiCalls.js
Labels: impact-high, system-wide

#1386 Change steps based on the config
  src/App.tsx
  src/Assets/pageTitleTags.ts
  src/Assets/stepDirectory.ts
  src/Components/Config/configHook.tsx
  src/Components/Confirmation/Confirmation.css
  src/Components/Confirmation/Confirmation.js
  src/Components/Confirmation/ConfirmationBlock.tsx
  src/Components/Confirmation/ConfirmationSteps.tsx
  src/Components/HouseholdDataBlock/HouseholdDataBlock.js
  src/Components/MoreHelp/MoreHelp.tsx
  src/Components/OptionCardGroup/OptionCardGroup.js
  src/Components/PreviousButton/PreviousButton.tsx
  src/Components/ProgressBar/ProgressBar.tsx
  src/Components/QuestionComponentContainer/QuestionComponentContainer.js
  src/Components/QuestionComponents/questionHooks.ts
  src/Components/Referrer/referrerHook.tsx
  src/Components/Results/Results.tsx
  src/Components/Steps/Disclaimer/Disclaimer.tsx
  src/Components/Steps/Expenses/Expenses.tsx
  src/Components/Steps/SelectLanguagePage.tsx
  src/Types/FormData.ts
Labels: impact-high, system-wide

#1391 Trim input text
  src/Components/Steps/Expenses/Expenses.tsx
  src/Components/Steps/HouseholdSize.tsx
  src/Components/Steps/Referrer.tsx
  src/Components/Steps/ZipcodeStep.tsx
Labels: system-wide

#1400 Replace current cdig logo
  src/Assets/States/CO/WhiteLabels/CCIG/ccigLandingPage.png
Labels: impact-low

#1398 Refactor immediate needs
  src/Assets/stepDirectory.ts
  src/Assets/updateScreen.ts
  src/Components/OptionCardGroup/MultiSelectTiles.css
  src/Components/OptionCardGroup/MultiSelectTiles.tsx
  src/Components/QuestionComponentContainer/QuestionComponentContainer.js
  src/Components/Steps/ImmediateNeeds.tsx
  src/Types/FormData.ts
Labels: impact-high, system-wide

#1399 Refactor current benefits
  src/App.tsx
  src/Assets/BenefitCategoryLists/benefitAccordions.ts
  src/Assets/questions.tsx
  src/Assets/updateScreen.ts
  src/Assets/validationFunctions.tsx
  src/Components/AccordionsContainer/AccordionsContainer.css
  src/Components/AccordionsContainer/AccordionsContainer.tsx
  src/Components/AccordionsContainer/CheckboxAccordion.css
  src/Components/AccordionsContainer/CheckboxAccordion.tsx
  src/Components/CategoryAccordion/CategoryAccordion.tsx
  src/Components/CheckboxGroup/CurrentBenefitsCheckboxGroup.tsx
  src/Components/ErrorMessage/ErrorMessageWrapper.tsx
  src/Components/FollowUpQuestions/FollowUpQuestions.js
  src/Components/QuestionComponentContainer/QuestionComponentContainer.js
  src/Components/Steps/AlreadyHasBenefits.tsx
  src/Components/Steps/Expenses/Expenses.tsx
  src/Types/ApiFormData.ts
  src/Types/FormData.ts
Labels: impact-high, system-wide
