Repository Gary-Community-Ventures/benefits-calculator, pull requests merged in 2024-10, with the labels that each got.

#1328 Ask birth month and year instead of age
  src/Assets/updateScreen.ts
  src/Assets/validationFunctions.tsx
  src/Components/AutoComplete/AutoComplete.tsx
  src/Components/Confirmation/Confirmation.js
  src/Components/FetchScreen/FetchScreen.tsx
  src/Components/HouseholdDataBlock/AgeInput.css
  src/Components/HouseholdDataBlock/AgeInput.tsx
  src/Components/HouseholdDataBlock/HouseholdDataBlock.js
  src/Types/ApiFormData.ts
  src/Types/FormData.ts
Labels: impact-high, system-wide

#1334 Refactor/household size
  src/Assets/questions.tsx
  src/Components/QuestionComponentContainer/QuestionComponentContainer.js
  src/Components/QuestionComponents/questionHooks.ts
  src/Components/Steps/HouseholdSize.tsx
  src/Components/Steps/ZipcodeStep.tsx
  src/Types/FormData.ts
  src/Types/Questions.ts
Labels: impact-high

#1349 Sign up privacy policy link
  src/Components/SignUp/SignUp.js
Labels: impact-low
