Repository Gary-Community-Ventures/benefits-calculator, pull requests merged in 2024-07, with the labels that each got.

#1168 Update dependencies
  package-lock.json
  package.json
Labels: impact-medium

#1182 Use the language in the URL
  src/Components/Wrapper/Wrapper.tsx
Labels: impact-medium

#1183 Run GitHub Actions When the Base Branch Changes
  .github/workflows/enforcer.yaml
Labels: impact-low

#1187 Fix loading for the referrer dropdown menu
  src/App.tsx
  src/Components/FetchScreen/FetchScreen.tsx
  src/Components/Wrapper/Wrapper.tsx
  src/Types/WrapperContext.ts
Labels: impact-medium

#1191 Citizen Filter
  src/Assets/citizenshipFilterFormControlLabels.tsx
Labels: impact-low

#1193 Citizen Help Bubble
  src/Assets/icons/helpBubble.svg
  src/Components/Results/Programs/Filter.tsx
Labels: impact-low

#1194 Language Page UUID
  src/Components/LandingPage/LandingPage.tsx
  src/Components/SelectLanguagePage/SelectLanguagePage.tsx
Labels: impact-low

#1197 Translate logo alts
  src/Components/Header/Header.js
  src/Components/Referrer/referrerHook.tsx
  src/Components/TwoOneOneComponents/TwoOneOneHeader/TwoOneOneHeader.js
Labels: impact-low

#1188 Feat/inputField
  package-lock.json
  package.json
  src/App.tsx
  src/Assets/questions.tsx
  src/Assets/validationFunctions.tsx
  src/Components/QuestionComponentContainer/QuestionComponentContainer.js
  src/Components/Steps/ZipcodeStep.tsx
  src/Components/Wrapper/Wrapper.tsx
  src/Types/Questions.ts
Labels: impact-high

#1210 Add Languages to the Navigator Type
  src/Types/Results.ts
Labels: impact-low

#1208 Empty messages are showing up as the label
  src/Components/Confirmation/Confirmation.js
  src/Components/LandingPage/LandingPage.tsx
  src/Components/SignUp/SignUp.js
Labels: bug, impact-low

#1209 Use Other Referrer Source if the Source is Other
  src/App.tsx
Labels: bug, impact-low
