Repository Gary-Community-Ventures/benefits-calculator, pull requests merged in 2024-08, with the labels that each got.

#1213 Update Household Size Help Bubble
  src/Assets/questions.tsx
Labels: impact-low

#1230 Go to next step hook
  src/Components/Confirmation/Confirmation.js
  src/Components/CurrentBenefits/CurrentBenefits.tsx
  src/Components/ExpenseBlock/ExpenseQuestion.js
  src/Components/FollowUpQuestions/FollowUpQuestions.js
  src/Components/HelpBubbleIcon/HelpButton.tsx
  src/Components/HouseholdDataBlock/HouseholdDataBlock.js
  src/Components/IncomeBlock/IncomeQuestion.js
  src/Components/IncomeBlock/PersonIncomeBlock.js
  src/Components/LandingPage/LandingPage.tsx
  src/Components/QuestionComponentContainer/QuestionComponentContainer.css
  src/Components/QuestionComponentContainer/QuestionComponentContainer.js
  src/Components/QuestionComponents/QuestionDescription.tsx
  src/Components/QuestionComponents/QuestionHeader.tsx
  src/Components/QuestionComponents/QuestionLeadText.tsx
  src/Components/QuestionComponents/QuestionQuestion.tsx
  src/Components/QuestionComponents/questionHooks.ts
  src/Components/SelectLanguagePage/SelectLanguagePage.tsx
  src/Components/Steps/ZipcodeStep.tsx
Labels: impact-low

#1228 Refactor question headers
  src/Components/Confirmation/Confirmation.js
  src/Components/CurrentBenefits/CurrentBenefits.tsx
  src/Components/ExpenseBlock/ExpenseQuestion.js
  src/Components/FollowUpQuestions/FollowUpQuestions.js
  src/Components/HelpBubbleIcon/HelpButton.tsx
  src/Components/HouseholdDataBlock/HouseholdDataBlock.js
  src/Components/IncomeBlock/IncomeQuestion.js
  src/Components/IncomeBlock/PersonIncomeBlock.js
  src/Components/LandingPage/LandingPage.tsx
  src/Components/QuestionComponentContainer/QuestionComponentContainer.css
  src/Components/QuestionComponentContainer/QuestionComponentContainer.js
  src/Components/SelectLanguagePage/SelectLanguagePage.tsx
  src/Components/Steps/ZipcodeStep.tsx
  src/Components/Titles/QuestionDescription.tsx
  src/Components/Titles/QuestionHeader.tsx
  src/Components/Titles/QuestionLeadText.tsx
  src/Components/Titles/QuestionQuestion.tsx
Labels: impact-medium

#1237 CCIG
  src/App.tsx
  src/Assets/CCIG/ccigLandingPage.png
  src/Assets/CCIG/ccigLogo.png
  src/Assets/stepDirectory.ts
  src/Components/CcigComponents/CcigLandingPage.css
  src/Components/CcigComponents/CcigLandingPage.tsx
  src/Components/CcigComponents/CcigResultsMessage.tsx
  src/Components/LandingPage/LandingPage.tsx
  src/Components/QuestionComponentContainer/QuestionComponentContainer.js
  src/Components/QuestionComponents/questionHooks.ts
  src/Components/Referrer/Referrer.tsx
  src/Components/Referrer/referrerDataInfo.tsx
  src/Components/Results/Programs/Programs.tsx
  src/Components/SelectLanguagePage/SelectLanguagePage.tsx
Labels: impact-medium

#1240 Refactor/back button
  src/Components/PrevAndContinueButtons/PrevAndContinueButtons.tsx
  src/Components/PreviousButton/PreviousButton.tsx
  src/Components/QuestionComponents/questionHooks.ts
  src/Components/Results/ProgramPage/ProgramPage.css
  src/Components/Steps/ZipcodeStep.tsx
Labels: impact-medium

#1247 Language Router
  src/App.tsx
  src/Components/LanguageRouter/LanguageRouter.tsx
  src/Components/Results/ProgramPage/ProgramPage.tsx.orig
Labels: impact-high

#1254 Use new warning_messages field
  src/Components/Results/ProgramPage/ProgramPage.css
  src/Components/Results/ProgramPage/ProgramPage.tsx
  src/Components/WarningComponent/WarningMessage.css
  src/Types/Results.ts
Labels: impact-medium
