Repository Gary-Community-Ventures/benefits-calculator, pull requests merged in 2024-06, with the labels that each got.

#1113 Expense Question Label
  src/Components/ExpenseBlock/ExpenseQuestion.js
Labels: impact-low

#1124 Feat/list co bens
  src/App.tsx
  src/Assets/colorado-mfb-logo.png
  src/Components/CurrentBenefits/CurrentBenefits.css
  src/Components/CurrentBenefits/CurrentBenefits.tsx
  src/Components/Referrer/referrerHook.ts
  src/Types/WrapperContext.ts
  src/apiCalls.js
Labels: impact-high

#1137 Feat/dhs cobrand
  src/Assets/DenverHumanServices/denverHSLogo.png
  src/Assets/referralOptions.tsx
  src/Components/Referrer/referrerHook.ts
Labels: impact-low

#1146 Fix the Referrer Source Selection
  src/App.tsx
Labels: impact-medium

#1148 Add has_fatc and has_nfp
  src/Assets/updateScreen.ts
  src/Components/FetchScreen/FetchScreen.tsx
  src/Types/ApiFormData.ts
  src/Types/FormData.ts
Labels: impact-low
