Repository Gary-Community-Ventures/benefits-calculator, pull requests merged in 2024-05, with the labels that each got.

#1046 Feat/more help
  src/App.tsx
  src/Components/MoreHelp/MoreHelp.css
  src/Components/MoreHelp/MoreHelp.tsx
  src/Components/Results/211Button/211Button.css
  src/Components/Results/211Button/211Button.tsx
  src/Components/Results/Results.tsx
Labels: impact-low

#1041 Update Sign Up Consent Language
  src/Components/SignUp/SignUp.js
Labels: impact-low

#1053 Override Estimated Value
  src/Components/Results/CategoryHeading/CategoryHeading.tsx
  src/Components/Results/FormattedValue.tsx
  src/Components/Results/ProgramPage/ProgramPage.tsx
  src/Components/Results/Programs/ProgramCard.tsx
  src/Components/Results/Results.tsx
  src/Components/Results/ResultsHeader/ResultsHeader.tsx
  src/Types/Results.ts
Labels: impact-high

#1055 Add Multiple Tax Units Error Message
  src/Components/Results/ProgramPage/ProgramPage.tsx
  src/Types/Results.ts
Labels: impact-low

#1058 Remove LGS and Tax Assistance Site
  src/Assets/referralOptions.tsx
Labels: impact-low

#1103 Refactor/footer
  package-lock.json
  src/App.css
  src/App.tsx
  src/Components/Footer/Footer.css
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.tsx
  src/Components/Header/Header.js
  src/Components/Share/Share.css
  src/Components/Share/Share.js
  src/Components/Share/Share.tsx
Labels: impact-low

#1106 Job Resources
  src/Assets/acuteConditionOptions.tsx
Labels: impact-medium
