Repository Gary-Community-Ventures/benefits-calculator, pull requests merged in 2025-03, with the labels that each got.

#1547 Redirect white label route to step one.
  src/App.tsx
  src/Components/EnergyCalculator/Results/RebatePageMappings.tsx
  src/Components/FetchScreen/FetchScreen.tsx
  src/Components/RouterUtil/RedirectToWhiteLabel.tsx
  src/Components/RouterUtil/WhiteLabelRouter.tsx
  src/Components/Steps/SelectStatePage.tsx
  src/Types/WhiteLabel.ts
Labels: impact-medium

#1555 1526 Clean up the immigration filter styling
  src/Components/Results/Programs/Filter.css
  src/Components/Results/Programs/Filter.tsx
Labels: bug, ctd

#1560 Redirect http to https
  static.json
Labels: impact-low

#1571 Redirect http to https for real this time.
  src/App.tsx
  src/Components/Wrapper/Wrapper.tsx
  static.json
Labels: impact-medium

#1572 Energy calculator copy edits
  src/Assets/languageOptions.tsx
  src/Components/EnergyCalculator/LandingPage/LandingPage.tsx
  src/Components/EnergyCalculator/Results/RebatePage.css
  src/Components/EnergyCalculator/Results/RebatePage.tsx
  src/Components/EnergyCalculator/Results/RebatePageMappings.tsx
  src/Components/EnergyCalculator/Steps/Appliances.tsx
  src/Components/EnergyCalculator/Steps/Expenses.tsx
  src/Components/EnergyCalculator/Steps/GasProvider.tsx
  src/Components/EnergyCalculator/Steps/HouseholdMemberForm.tsx
  src/Components/HelpBubbleIcon/HelpButton.tsx
  src/Components/Results/Programs/Filter.tsx
  src/Components/Steps/AlreadyHasBenefits.tsx
  src/Components/Steps/Expenses/Expenses.tsx
  src/Components/Steps/HouseholdAssets/HouseholdAssets.tsx
  src/Components/Steps/HouseholdMembers/HouseholdMemberForm.tsx
  src/Components/Steps/HouseholdSize.tsx
  src/Components/Steps/SignUp/SignUp.tsx
Labels: impact-medium

#1575 Update sign up page
  src/Assets/updateScreen.ts
  src/Components/EnergyCalculator/Steps/Disclaimer.tsx
  src/Components/Steps/Disclaimer/Disclaimer.tsx
  src/Components/Steps/SignUp/SignUp.tsx
  src/Types/ApiFormData.ts
Labels: impact-high

#1577 Refactor/energy calc rebate cards
  src/Assets/updateScreen.ts
  src/Components/EnergyCalculator/Results/RebateCategories.tsx
  src/Components/EnergyCalculator/Results/RebatePage.css
  src/Components/EnergyCalculator/Results/RebatePage.tsx
  src/Components/EnergyCalculator/Results/rebateTypes.tsx
  src/Components/EnergyCalculator/Steps/Appliances.tsx
  src/Components/EnergyCalculator/hooks.ts
  src/Components/FetchScreen/FetchScreen.tsx
  src/Types/ApiFormData.ts
  src/Types/FormData.ts
Labels: impact-medium
