Repository Gary-Community-Ventures/benefits-calculator, pull requests merged in 2025-02, with the labels that each got.

#1481 Add NC Weatherization program to screener
  src/Assets/updateScreen.ts
  src/Components/FetchScreen/FetchScreen.tsx
  src/Types/ApiFormData.ts
Labels: ctd, nc specific

#1474 Add section 8 to has benefits
  src/Assets/updateScreen.ts
  src/Components/FetchScreen/FetchScreen.tsx
  src/Components/Steps/AlreadyHasBenefits.tsx
  src/Types/ApiFormData.ts
Labels: impact-low

#1484 Energy calculator: renter expenses
  src/Assets/updateScreen.ts
  src/Components/Confirmation/ConfirmationSteps.tsx
  src/Components/EnergyCalculator/ConfirmationPage/ElectricityProvider.tsx
  src/Components/EnergyCalculator/ConfirmationPage/Expenses.tsx
  src/Components/EnergyCalculator/Icons/AcUnit.svg
  src/Components/EnergyCalculator/Icons/Heat.svg
  src/Components/EnergyCalculator/Icons/LowFuel.svg
  src/Components/EnergyCalculator/Icons/Plug.svg
  src/Components/EnergyCalculator/Icons/Stove.svg
  src/Components/EnergyCalculator/Icons/Washer.svg
  src/Components/EnergyCalculator/Icons/WaterHeater.svg
  src/Components/EnergyCalculator/Steps/ElectricityProvider.tsx
  src/Components/EnergyCalculator/Steps/Expenses.tsx
  src/Components/EnergyCalculator/electricityProviders.ts
  src/Components/EnergyCalculator/hooks.ts
  src/Components/FetchScreen/FetchScreen.tsx
  src/Components/OptionCardGroup/MultiSelectTiles.tsx
  src/Components/QuestionComponentContainer/QuestionComponentContainer.tsx
  src/Components/Steps/SelectHelperFunctions/SelectHelperFunctions.tsx
  src/Types/ApiFormData.ts
  src/Types/FormData.ts
  src/Types/Questions.ts
Labels: impact-medium

#1472 Electricity provider step
  src/Components/EnergyCalculator/Steps/ElectricityProvider.tsx
Labels: impact-medium

#1475 Paths
  src/App.tsx
  src/Assets/stepDirectory.ts
  src/Assets/updateScreen.ts
  src/Components/FetchScreen/FetchScreen.tsx
  src/Components/QuestionComponents/questionHooks.ts
  src/Components/Referrer/referrerHook.tsx
  src/Types/ApiFormData.ts
  src/Types/FormData.ts
Labels: impact-high

#1498 Small energy updates
  src/Assets/pageTitleTags.ts
  src/Components/Confirmation/ConfirmationSteps.tsx
  src/Components/EnergyCalculator/ConfirmationPage/ElectricityProvider.tsx
  src/Components/EnergyCalculator/ConfirmationPage/GasProvider.tsx
  src/Components/EnergyCalculator/Steps/Appliances.tsx
  src/Components/EnergyCalculator/Steps/ElectricityProvider.tsx
  src/Components/EnergyCalculator/Steps/Expenses.tsx
  src/Components/EnergyCalculator/Steps/GasProvider.tsx
  src/Components/QuestionComponentContainer/QuestionComponentContainer.tsx
  src/Types/Questions.ts
Labels: impact-low

#1500 Jeffco Public Schools logo
  src/Assets/States/CO/WhiteLabels/JeffcoAssets/jeffcopublicschoolslogo.png
  src/Components/Referrer/referrerDataInfo.tsx
Labels: impact-low

#1519 Don't show category value when the value is 0
  src/Components/Results/CategoryHeading/CategoryHeading.tsx
Labels: impact-low

#1525 Add "Powered by MFB" footer component
  src/Assets/Logos/powered_by_mfb.png
  src/Components/Footer/PoweredByFooter.css
  src/Components/Footer/PoweredByFooter.tsx
  src/Components/ProgressBar/ProgressBar.tsx
  src/Components/Referrer/Referrer.tsx
  src/Components/Referrer/referrerDataInfo.tsx
Labels: impact-medium

#1520 Fix Swahili url
  src/Assets/languageOptions.tsx
  src/Components/Results/ProgramPage/NavigatorLanguages.tsx
  src/Types/Language.ts
Labels: impact-low
