Repository Gary-Community-Ventures/benefits-calculator, pull requests merged in 2025-04, with the labels that each got.

#1598 Add Pitkin county cobrand
  src/Assets/States/CO/WhiteLabels/PitkenCounty/PitkinCountyLogo.png
  src/Components/Header/Header.css
  src/Components/Referrer/referrerDataInfo.tsx
Labels: impact-low

#1517 Updating form data from api responses
  src/Assets/updateFormData.tsx
  src/Assets/updateScreen.ts
  src/Components/DropdownMenu/BasicSelect.tsx
  src/Components/DropdownMenu/DropdownMenu.tsx
  src/Components/EnergyCalculator/Steps/Appliances.tsx
  src/Components/EnergyCalculator/Steps/Disclaimer.tsx
  src/Components/EnergyCalculator/Steps/ElectricityProvider.tsx
  src/Components/EnergyCalculator/Steps/Expenses.tsx
  src/Components/EnergyCalculator/Steps/GasProvider.tsx
  src/Components/EnergyCalculator/Steps/HouseholdMemberForm.tsx
  src/Components/EnergyCalculator/Steps/Utilities.tsx
  src/Components/FetchScreen/FetchScreen.tsx
  src/Components/PreviousButton/PreviousButton.tsx
  src/Components/QuestionComponents/questionHooks.ts
  src/Components/Results/ProgramPage/ProgramPage.tsx
  src/Components/Steps/AlreadyHasBenefits.tsx
  src/Components/Steps/Disclaimer/Disclaimer.tsx
  src/Components/Steps/Expenses/Expenses.tsx
  src/Components/Steps/HouseholdAssets/HouseholdAssets.tsx
  src/Components/Steps/HouseholdMembers/HHMSummaryCards.tsx
  src/Components/Steps/HouseholdMembers/HouseholdMemberForm.tsx
  src/Components/Steps/HouseholdSize.tsx
  src/Components/Steps/ImmediateNeeds.tsx
  src/Components/Steps/Referrer.tsx
  src/Components/Steps/SelectLanguage.tsx
  src/Components/Steps/SignUp/SignUp.tsx
  src/Components/Steps/Zipcode.tsx
  src/Types/FormData.ts
  src/Types/WrapperContext.ts
  src/apiCalls.ts
Labels: impact-high

#1578 Massachusetts
  src/Assets/updateScreen.ts
  src/Components/EnergyCalculator/Results/RebatePage.css
  src/Components/Steps/Disclaimer/Disclaimer.tsx
  src/Components/Steps/HouseholdMembers/HouseholdMemberForm.tsx
  src/Components/Steps/Zipcode.tsx
  src/Types/ApiFormData.ts
  src/Types/FormData.ts
  static.json
Labels: impact-high

#1602 Update green card filter text
  src/Assets/citizenshipFilterFormControlLabels.tsx
Labels: impact-low

#1605 Central: TCPA checkbox in signup form only if entering cell phone
  src/Components/Steps/SignUp/SignUp.tsx
Labels: impact-medium

#1621 Energy: Pass query params from the landing page
  src/Components/EnergyCalculator/LandingPage/LandingPage.tsx
  src/Components/QuestionComponents/questionHooks.ts
Labels: impact-low

#1619 Central: Members caps
  src/Components/Results/FormattedValue.tsx
  src/Types/Results.ts
Labels: impact-medium

#1627 Central: Correct zip code error message
  src/Components/Steps/Zipcode.tsx
Labels: impact-low

#1632 MA: Fixes
  src/Assets/icons/UrgentNeeds/AcuteConditions/military.svg
  src/Assets/updateFormData.tsx
  src/Assets/updateScreen.ts
  src/Components/Config/configHook.tsx
  src/Types/ApiFormData.ts
Labels: impact-low
